In [65]:
import pandas as pd
import os
import glob

In [66]:
# Load CSV files into a list
# csv_files = ["https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/Australia_Wine_Stats.csv",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/Chile_Wine_Stats.csv",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/France_Wine_Stats.csv",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/Italy_Wine_Stats.csv", 
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/New%20Zealand_Wine_Stats.csv",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/Portugal_Wine_Stats.csv",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/Spain_Wine_Stats.csv ",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/USA_Wine_Stats.csv"]  




csv_files = glob.glob("../Wine_Stats/*.csv") 
data_frames = [pd.read_csv(file) for file in csv_files]

# Concatenate into a single DataFrame
wine_df = pd.concat(data_frames, ignore_index=True)

# Display the first few rows
wine_df.head()

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic
0,0,Fields Of Joy Shiraz 2014,4.0,203,28.99,Australia / South Australia / Mount Lofty Rang...,Two Hands,Australian Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,47.13000,20.62,43.570
1,1,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.500000,"Mourvedre, Shiraz/Syrah, Grenache","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.000
2,2,Passion has Red Lips 2020,3.8,350,27.50,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.780
3,3,The Hermit Crab Viognier - Marsanne 2018,3.8,1026,16.99,Australia / South Australia / Fleurieu / McLar...,d'Arenberg,NaN,13.794543,NaN,[],61.73,46.29527,9.05,53.555
4,4,Cabernet Sauvignon (Batch No. 1 & 3) 2019,3.8,969,14.99,Australia / South Eastern Australia,Gentleman's Collection,Australian Cabernet Sauvignon,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",76.34,49.36000,16.02,47.890

In [67]:
# Display the first few rows of the DataFrame
print(wine_df.head())

# Display the DataFrame structure (columns and data types)
print(wine_df.info())

# Summary statistics for numerical columns
print(wine_df.describe())

   Unnamed: 0                                       Name  Rating  \
0           0                  Fields Of Joy Shiraz 2014     4.0
1           1                          Shotfire GSM 2018     3.9
2           2                  Passion has Red Lips 2020     3.8
3           3   The Hermit Crab Viognier - Marsanne 2018     3.8
4           4  Cabernet Sauvignon (Batch No. 1 & 3) 2019     3.8

   Number of Ratings  Price  \
0                203  28.99
1                 36  19.49
2                350  27.50
3               1026  16.99
4                969  14.99

                                              Region                  Winery  \
0  Australia / South Australia / Mount Lofty Rang...               Two Hands
1              Australia / South Australia / Barossa            Thorn-Clarke
2  Australia / South Australia / Fleurieu / McLar...        Some Young Punks
3  Australia / South Australia / Fleurieu / McLar...              d'Arenberg
4                Australia / South Eastern Australia  Gentleman's Collection

                      Wine style  Alcohol content  \
0              Australian Shiraz        13.794543
1     Australian Rhône Blend Red        14.500000
2   Australian Cabernet - Shiraz        13.794543
3                            NaN        13.794543
4  Australian Cabernet Sauvignon        13.794543

                              Grapes  \
0                                NaN
1  Mourvedre, Shiraz/Syrah, Grenache
2                                NaN
3                                NaN
4                                NaN

                                       Food pairings   Bold    Tannin  Sweet  \
0  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  47.13000  20.62
1  ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']  85.00  50.63000   9.05
2                        ['Beef', 'Lamb', 'Poultry']  85.00  49.37000   8.19
3                                                 []  61.73  46.29527   9.05
4                        ['Beef', 'Lamb', 'Poultry']  76.34  49.36000  16.02

   Acidic
0  43.570
1  43.000
2  44.780
3  53.555
4  47.890
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5145 entries, 0 to 5144
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5145 non-null   int64
 1   Name               5145 non-null   object
 2   Rating             5145 non-null   float64
 3   Number of Ratings  5145 non-null   int64
 4   Price              5145 non-null   float64
 5   Region             5145 non-null   object
 6   Winery             5142 non-null   object
 7   Wine style         4624 non-null   object
 8   Alcohol content    5145 non-null   float64
 9   Grapes             2977 non-null   object
 10  Food pairings      5145 non-null   object
 11  Bold               5145 non-null   float64
 12  Tannin             5145 non-null   float64
 13  Sweet              5145 non-null   float64
 14  Acidic             5145 non-null   float64
dtypes: float64(7), int64(2), object(6)
memory usage: 603.1+ KB
None
        Unnamed: 0       Rating  Number of Ratings        Price  \
count  5145.000000  5145.000000        5145.000000  5145.000000
mean    503.271914     4.000292         601.032653    27.424618
std     406.492427     0.157726        2725.500208    10.645818
min       0.000000     3.700000          25.000000     6.500000
25%     164.000000     3.900000          73.000000    19.980000
50%     377.000000     4.000000         189.000000    25.990000
75%     790.000000     4.100000         483.000000    34.000000
max    1436.000000     4.600000      159937.000000   155.000000

       Alcohol content         Bold       Tannin        Sweet       Acidic
count      5145.000000  5145.000000  5145.000000  5145.000000  5145.000000
mean         13.794363    57.990384    46.293535    12.259602    54.096125
std           1.242644    19.081310    11.092394    12.306948    14.463969
min           5.000000     0.060000     1.400000     0.010000     7.230000
25%          13.500000    45.330000    46.295270     6.230000    44.700000
50%          13.794543    61.730000    46.295270     9.050000    53.555000
75%          14.000000    69.620000    48.610000    13.200000    63.550000
max          20.500000    85.000000    85.000000    85.000000    85.000000

In [68]:
# Remove duplicate rows from the DataFrame
# wine_df = wine_df.drop_duplicates()

# Verify by checking the shape of the DataFrame before and after
print("Before removing duplicates:", wine_df.shape)
wine_df = wine_df.drop_duplicates()
print("After removing duplicates:", wine_df.shape)

Before removing duplicates: (5145, 15)
After removing duplicates: (5145, 15)

In [69]:
# Drop rows with any null values
wine_df = wine_df.dropna()

# Verify by checking the shape of the DataFrame
print("After dropping rows with null values:", wine_df.shape)

After dropping rows with null values: (2977, 15)

In [70]:
# Split the 'Region' column by '/' and create separate columns for 'Country' and 'Region Detail'
wine_df['Country'] = wine_df['Region'].str.split('/').str[0].str.strip()  # First part as 'Country'
wine_df['Country_Region'] = wine_df['Region'].str.split('/').str[1].str.strip()  # Second part as 'Country_Region'

# Display the first few rows to confirm the changes
print(wine_df[['Region', 'Country', 'Country_Region']].head())
print(wine_df)

                                              Region    Country  \
1              Australia / South Australia / Barossa  Australia
5  Australia / South Australia / Fleurieu / McLar...  Australia
7  Australia / South Australia / Fleurieu / McLar...  Australia
8              Australia / South Australia / Barossa  Australia
9  Australia / South Australia / Barossa / Baross...  Australia

    Country_Region
1  South Australia
5  South Australia
7  South Australia
8  South Australia
9  South Australia
      Unnamed: 0                          Name  Rating  Number of Ratings  \
1              1             Shotfire GSM 2018     3.9                 36
5              5     Passion has Red Lips 2014     3.8                648
7              7            Jester Shiraz 2018     3.9                658
8              8        Shotfire Quartage 2016     3.8                 93
9              9        Stonehorse Shiraz 2018     4.0                288
...          ...                           ...     ...                ...
5138         665  Sonoma Coast Pinot Noir 2013     4.1                193
5139         666             Dry Riesling 2015     3.9                184
5141         668      Pessimist Red Blend 2020     4.0                574
5142         669       Cabernet Sauvignon 2013     3.8               4612
5144         671     Freakshow Chardonnay 2020     3.8                160

      Price                                             Region  \
1     19.49              Australia / South Australia / Barossa
5     18.49  Australia / South Australia / Fleurieu / McLar...
7     22.00  Australia / South Australia / Fleurieu / McLar...
8     17.99              Australia / South Australia / Barossa
9     29.17  Australia / South Australia / Barossa / Baross...
...     ...                                                ...
5138  39.99  United States / California / North Coast / Son...
5139  24.99  United States / California / North Coast / Nap...
5141  17.99  United States / California / Central Coast / S...
5142  34.99  United States / California / Central Coast / S...
5144  17.99  United States / California / Central Valley / ...

                    Winery                      Wine style  Alcohol content  \
1             Thorn-Clarke      Australian Rhône Blend Red             14.5
5         Some Young Punks    Australian Cabernet - Shiraz             14.5
7                   Mitolo               Australian Shiraz             14.5
8             Thorn-Clarke       Australian Bordeaux Blend             14.5
9                  Kaesler               Australian Shiraz             14.0
...                    ...                             ...              ...
5138               Red Car          Californian Pinot Noir             13.3
5139             Trefethen            Californian Riesling             12.5
5141                  DAOU           Californian Red Blend             15.2
5142        Liberty School  Californian Cabernet Sauvignon             13.5
5144  Michael David Winery          Californian Chardonnay             13.5

                                          Grapes  \
1              Mourvedre, Shiraz/Syrah, Grenache
5         70 Shiraz/Syrah, 30 Cabernet Sauvignon
7                               100 Shiraz/Syrah
8     Cabernet Franc, Malbec, Cabernet Sauvignon
9                               100 Shiraz/Syrah
...                                          ...
5138                              100 Pinot Noir
5139                                100 Riesling
5141                                   100 Durif
5142                      100 Cabernet Sauvignon
5144                              100 Chardonnay

                                          Food pairings   Bold    Tannin  \
1     ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']  85.00  50.63000
5                           ['Beef', 'Lamb', 'Poultry']  85.00  49.37000
7     ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  46.65000
8     ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison...  85.00  56.40000
9     ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  84.04  44.21000
...                                                 ...    ...       ...
5138  ['Beef', 'Veal', 'Game (deer, venison)', 'Poul...  38.89  19.57000
5139  ['Pork', 'Shellfish', 'Spicy food', 'Poultry',...  41.61  46.29527
5141                ['Beef', 'Lamb', 'Veal', 'Poultry']  85.00  53.43000
5142  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  49.14000
5144  ['Pork', 'Rich fish (salmon, tuna etc)', 'Vege...  77.65  46.29527

      Sweet  Acidic        Country   Country_Region
1      9.05   43.00      Australia  South Australia
5      8.19   44.78      Australia  South Australia
7     19.07   44.18      Australia  South Australia
8     10.85   65.28      Australia  South Australia
9     22.10   41.95      Australia  South Australia
...     ...     ...            ...              ...
5138   7.58   54.96  United States       California
5139   1.21   69.68  United States       California
5141  15.96   61.84  United States       California
5142   9.63   42.02  United States       California
5144  33.83   47.48  United States       California

[2977 rows x 17 columns]

In [71]:
# Check for duplicate rows in the DataFrame
print("\nDuplicate records:")
print(wine_df.duplicated().sum())

Duplicate records:
0

No duplicates

In [72]:
# Calculate and display the percentage of missing values
print("\missing values percentage:")
missing_percentage = (wine_df.isnull().sum() / len(wine_df)) * 100
print(missing_percentage)

\missing values percentage:
Unnamed: 0           0.000000
Name                 0.000000
Rating               0.000000
Number of Ratings    0.000000
Price                0.000000
Region               0.000000
Winery               0.000000
Wine style           0.000000
Alcohol content      0.000000
Grapes               0.000000
Food pairings        0.000000
Bold                 0.000000
Tannin               0.000000
Sweet                0.000000
Acidic               0.000000
Country              0.000000
Country_Region       0.134363
dtype: float64

<>:2: SyntaxWarning: invalid escape sequence '\m'
<>:2: SyntaxWarning: invalid escape sequence '\m'
C:\Users\ASUS\AppData\Local\Temp\ipykernel_24096\621265348.py:2: SyntaxWarning: invalid escape sequence '\m'
  print("\missing values percentage:")

If missing values are below 10%, dropping them might be fine; above 40% may result in significant data loss

In [73]:
# Since more than 40% of the 'Grapes' column is missing, it will be dropped as it's not critical for analysis
wine_df = wine_df.drop(columns=['Grapes'])
print(wine_df)

      Unnamed: 0                          Name  Rating  Number of Ratings  \
1              1             Shotfire GSM 2018     3.9                 36
5              5     Passion has Red Lips 2014     3.8                648
7              7            Jester Shiraz 2018     3.9                658
8              8        Shotfire Quartage 2016     3.8                 93
9              9        Stonehorse Shiraz 2018     4.0                288
...          ...                           ...     ...                ...
5138         665  Sonoma Coast Pinot Noir 2013     4.1                193
5139         666             Dry Riesling 2015     3.9                184
5141         668      Pessimist Red Blend 2020     4.0                574
5142         669       Cabernet Sauvignon 2013     3.8               4612
5144         671     Freakshow Chardonnay 2020     3.8                160

      Price                                             Region  \
1     19.49              Australia / South Australia / Barossa
5     18.49  Australia / South Australia / Fleurieu / McLar...
7     22.00  Australia / South Australia / Fleurieu / McLar...
8     17.99              Australia / South Australia / Barossa
9     29.17  Australia / South Australia / Barossa / Baross...
...     ...                                                ...
5138  39.99  United States / California / North Coast / Son...
5139  24.99  United States / California / North Coast / Nap...
5141  17.99  United States / California / Central Coast / S...
5142  34.99  United States / California / Central Coast / S...
5144  17.99  United States / California / Central Valley / ...

                    Winery                      Wine style  Alcohol content  \
1             Thorn-Clarke      Australian Rhône Blend Red             14.5
5         Some Young Punks    Australian Cabernet - Shiraz             14.5
7                   Mitolo               Australian Shiraz             14.5
8             Thorn-Clarke       Australian Bordeaux Blend             14.5
9                  Kaesler               Australian Shiraz             14.0
...                    ...                             ...              ...
5138               Red Car          Californian Pinot Noir             13.3
5139             Trefethen            Californian Riesling             12.5
5141                  DAOU           Californian Red Blend             15.2
5142        Liberty School  Californian Cabernet Sauvignon             13.5
5144  Michael David Winery          Californian Chardonnay             13.5

                                          Food pairings   Bold    Tannin  \
1     ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']  85.00  50.63000
5                           ['Beef', 'Lamb', 'Poultry']  85.00  49.37000
7     ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  46.65000
8     ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison...  85.00  56.40000
9     ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  84.04  44.21000
...                                                 ...    ...       ...
5138  ['Beef', 'Veal', 'Game (deer, venison)', 'Poul...  38.89  19.57000
5139  ['Pork', 'Shellfish', 'Spicy food', 'Poultry',...  41.61  46.29527
5141                ['Beef', 'Lamb', 'Veal', 'Poultry']  85.00  53.43000
5142  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  49.14000
5144  ['Pork', 'Rich fish (salmon, tuna etc)', 'Vege...  77.65  46.29527

      Sweet  Acidic        Country   Country_Region
1      9.05   43.00      Australia  South Australia
5      8.19   44.78      Australia  South Australia
7     19.07   44.18      Australia  South Australia
8     10.85   65.28      Australia  South Australia
9     22.10   41.95      Australia  South Australia
...     ...     ...            ...              ...
5138   7.58   54.96  United States       California
5139   1.21   69.68  United States       California
5141  15.96   61.84  United States       California
5142   9.63   42.02  United States       California
5144  33.83   47.48  United States       California

[2977 rows x 16 columns]

In [74]:
#The 'Wine style' column has about 10% missing values, so we will drop rows with missing values in this column
wine_df = wine_df.dropna(subset=['Wine style'])

In [75]:
# Display the updated DataFrame info
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2977 entries, 1 to 5144
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2977 non-null   int64
 1   Name               2977 non-null   object
 2   Rating             2977 non-null   float64
 3   Number of Ratings  2977 non-null   int64
 4   Price              2977 non-null   float64
 5   Region             2977 non-null   object
 6   Winery             2977 non-null   object
 7   Wine style         2977 non-null   object
 8   Alcohol content    2977 non-null   float64
 9   Food pairings      2977 non-null   object
 10  Bold               2977 non-null   float64
 11  Tannin             2977 non-null   float64
 12  Sweet              2977 non-null   float64
 13  Acidic             2977 non-null   float64
 14  Country            2977 non-null   object
 15  Country_Region     2973 non-null   object
dtypes: float64(7), int64(2), object(7)
memory usage: 395.4+ KB

In [76]:
# Create a new 'index' column starting from 1
wine_df.insert(0, "Index", range(1, len(wine_df) + 1))
wine_df.drop(columns=['Unnamed: 0'])

,Index,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Food pairings,Bold,Tannin,Sweet,Acidic,Country,Country_Region
1,1,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.5,"['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.00,Australia,South Australia
5,2,Passion has Red Lips 2014,3.8,648,18.49,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,14.5,"['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.78,Australia,South Australia
7,3,Jester Shiraz 2018,3.9,658,22.00,Australia / South Australia / Fleurieu / McLar...,Mitolo,Australian Shiraz,14.5,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,46.65000,19.07,44.18,Australia,South Australia
8,4,Shotfire Quartage 2016,3.8,93,17.99,Australia / South Australia / Barossa,Thorn-Clarke,Australian Bordeaux Blend,14.5,"['Beef', 'Pasta', 'Lamb', 'Game (deer, venison...",85.00,56.40000,10.85,65.28,Australia,South Australia
9,5,Stonehorse Shiraz 2018,4.0,288,29.17,Australia / South Australia / Barossa / Baross...,Kaesler,Australian Shiraz,14.0,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",84.04,44.21000,22.10,41.95,Australia,South Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5138,2973,Sonoma Coast Pinot Noir 2013,4.1,193,39.99,United States / California / North Coast / Son...,Red Car,Californian Pinot Noir,13.3,"['Beef', 'Veal', 'Game (deer, venison)', 'Poul...",38.89,19.57000,7.58,54.96,United States,California
5139,2974,Dry Riesling 2015,3.9,184,24.99,United States / California / North Coast / Nap...,Trefethen,Californian Riesling,12.5,"['Pork', 'Shellfish', 'Spicy food', 'Poultry',...",41.61,46.29527,1.21,69.68,United States,California
5141,2975,Pessimist Red Blend 2020,4.0,574,17.99,United States / California / Central Coast / S...,DAOU,Californian Red Blend,15.2,"['Beef', 'Lamb', 'Veal', 'Poultry']",85.00,53.43000,15.96,61.84,United States,California
5142,2976,Cabernet Sauvignon 2013,3.8,4612,34.99,United States / California / Central Coast / S...,Liberty School,Californian Cabernet Sauvignon,13.5,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,49.14000,9.63,42.02,United States,California
5144,2977,Freakshow Chardonnay 2020,3.8,160,17.99,United States / California / Central Valley / ...,Michael David Winery,Californian Chardonnay,13.5,"['Pork', 'Rich fish (salmon, tuna etc)', 'Vege...",77.65,46.29527,33.83,47.48,United States,California

In [77]:
#Display the updated Dataframe
print(wine_df)

      Index  Unnamed: 0                          Name  Rating  \
1         1           1             Shotfire GSM 2018     3.9
5         2           5     Passion has Red Lips 2014     3.8
7         3           7            Jester Shiraz 2018     3.9
8         4           8        Shotfire Quartage 2016     3.8
9         5           9        Stonehorse Shiraz 2018     4.0
...     ...         ...                           ...     ...
5138   2973         665  Sonoma Coast Pinot Noir 2013     4.1
5139   2974         666             Dry Riesling 2015     3.9
5141   2975         668      Pessimist Red Blend 2020     4.0
5142   2976         669       Cabernet Sauvignon 2013     3.8
5144   2977         671     Freakshow Chardonnay 2020     3.8

      Number of Ratings  Price  \
1                    36  19.49
5                   648  18.49
7                   658  22.00
8                    93  17.99
9                   288  29.17
...                 ...    ...
5138                193  39.99
5139                184  24.99
5141                574  17.99
5142               4612  34.99
5144                160  17.99

                                                 Region                Winery  \
1                 Australia / South Australia / Barossa          Thorn-Clarke
5     Australia / South Australia / Fleurieu / McLar...      Some Young Punks
7     Australia / South Australia / Fleurieu / McLar...                Mitolo
8                 Australia / South Australia / Barossa          Thorn-Clarke
9     Australia / South Australia / Barossa / Baross...               Kaesler
...                                                 ...                   ...
5138  United States / California / North Coast / Son...               Red Car
5139  United States / California / North Coast / Nap...             Trefethen
5141  United States / California / Central Coast / S...                  DAOU
5142  United States / California / Central Coast / S...        Liberty School
5144  United States / California / Central Valley / ...  Michael David Winery

                          Wine style  Alcohol content  \
1         Australian Rhône Blend Red             14.5
5       Australian Cabernet - Shiraz             14.5
7                  Australian Shiraz             14.5
8          Australian Bordeaux Blend             14.5
9                  Australian Shiraz             14.0
...                              ...              ...
5138          Californian Pinot Noir             13.3
5139            Californian Riesling             12.5
5141           Californian Red Blend             15.2
5142  Californian Cabernet Sauvignon             13.5
5144          Californian Chardonnay             13.5

                                          Food pairings   Bold    Tannin  \
1     ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']  85.00  50.63000
5                           ['Beef', 'Lamb', 'Poultry']  85.00  49.37000
7     ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  46.65000
8     ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison...  85.00  56.40000
9     ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  84.04  44.21000
...                                                 ...    ...       ...
5138  ['Beef', 'Veal', 'Game (deer, venison)', 'Poul...  38.89  19.57000
5139  ['Pork', 'Shellfish', 'Spicy food', 'Poultry',...  41.61  46.29527
5141                ['Beef', 'Lamb', 'Veal', 'Poultry']  85.00  53.43000
5142  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  49.14000
5144  ['Pork', 'Rich fish (salmon, tuna etc)', 'Vege...  77.65  46.29527

      Sweet  Acidic        Country   Country_Region
1      9.05   43.00      Australia  South Australia
5      8.19   44.78      Australia  South Australia
7     19.07   44.18      Australia  South Australia
8     10.85   65.28      Australia  South Australia
9     22.10   41.95      Australia  South Australia
...     ...     ...            ...              ...
5138   7.58   54.96  United States       California
5139   1.21   69.68  United States       California
5141  15.96   61.84  United States       California
5142   9.63   42.02  United States       California
5144  33.83   47.48  United States       California

[2977 rows x 17 columns]

In [78]:
# Function to identify outliers based on the 1st and 99th percentiles
def find_percentile_outliers(df, columns, lower_percentile=1, upper_percentile=99):
    outlier_rows = {}

    for column in columns:
        # Calculate the lower and upper bounds based on percentiles
        lower_bound = df[column].quantile(lower_percentile / 100)
        upper_bound = df[column].quantile(upper_percentile / 100)
        
        # Find rows where values are outside the bounds
        outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)].index
        
        # Get the corresponding row numbers for these outliers
        outlier_row_numbers = df.loc[outliers, 'Index'].tolist()
        
        # Store the row numbers of outliers for each column
        outlier_rows[column] = outlier_row_numbers
    
    return outlier_rows

In [79]:
#Columns to check for outliers
columns_to_check = ['Rating', 'Price', 'Bold', 'Tannin', 'Sweet', 'Acidic']

In [80]:
# Find the rows with outliers in the specified columns
outlier_rows = find_percentile_outliers(wine_df, columns_to_check, lower_percentile=1, upper_percentile=99)

In [81]:
# Print the outlier row numbers for each column
for column, rows in outlier_rows.items():
    print(f"Outliers for column '{column}':")
    print(rows)
    print("\n")

Outliers for column 'Rating':
[463, 1013, 1377, 2127, 2203, 2438]


Outliers for column 'Price':
[67, 107, 132, 145, 249, 287, 316, 365, 446, 483, 486, 582, 600, 631, 640, 732, 801, 818, 880, 914, 916, 943, 957, 979, 980, 1000, 1008, 1038, 1056, 1109, 1319, 1496, 1569, 1655, 1713, 1779, 1854, 1890, 1905, 1937, 1950, 1965, 2025, 2047, 2161, 2174, 2247, 2250, 2267, 2302, 2345, 2349, 2364, 2402, 2404, 2477, 2516, 2694, 2725, 2960]


Outliers for column 'Bold':
[347, 417, 428, 452, 453, 456, 536, 570, 675, 709, 773, 854, 856, 866, 874, 891, 916, 919, 939, 946, 992, 997, 1042, 2071, 2104, 2253, 2269, 2315, 2374, 2502]


Outliers for column 'Tannin':
[225, 226, 238, 248, 261, 266, 311, 392, 417, 453, 456, 493, 515, 528, 536, 568, 709, 768, 773, 834, 854, 856, 866, 894, 904, 916, 919, 939, 946, 973, 997, 1042, 1057, 1059, 1149, 1157, 1192, 1196, 1214, 1226, 1264, 1266, 1272, 1288, 1331, 1342, 1364, 1368, 1387, 1460, 1499, 1568, 1612, 1651, 1688, 1722, 1742, 1770, 1832, 2662]


Outliers for column 'Sweet':
[319, 325, 344, 373, 441, 566, 658, 750, 785, 803, 821, 895, 901, 925, 947, 976, 978, 1031, 1124, 1181, 1193, 1398, 1460, 1547, 1675, 1702, 1714, 1920, 2415, 2723]


Outliers for column 'Acidic':
[18, 46, 61, 100, 151, 161, 182, 225, 226, 1277, 1330, 1707, 1793, 2588, 2599, 2601, 2623, 2627, 2649, 2731, 2738, 2750, 2766, 2771, 2792, 2870, 2918, 2934, 2938, 2944]

In [82]:
# Interpretation of the outliers
print("Interpretation:")
print("Outliers in the 'Rating,' 'Price,' 'Tannin,' 'Sweet,' 'Acidic,' and 'Bold' columns in wines are considered valid and should not be" 
      "removed due to domain-specific reasons. These outliers may represent rare but legitimate cases, such as premium products or exceptional"
      " ratings, which are important for accurately capturing the full range of wine characteristics.")

Interpretation:
Outliers in the 'Rating,' 'Price,' 'Tannin,' 'Sweet,' 'Acidic,' and 'Bold' columns in wines are considered valid and should not beremoved due to domain-specific reasons. These outliers may represent rare but legitimate cases, such as premium products or exceptional ratings, which are important for accurately capturing the full range of wine characteristics.

In [83]:
#Check for wines with alcohol content above 16% or below 9%
non_regular_wines = wine_df[(wine_df['Alcohol content'] > 16) | (wine_df['Alcohol content'] < 9)]
print(non_regular_wines)
print("Wines below 9% alcohol are low-alcohol wines, like Moscato or low-alcohol Riesling. Wines above 16% are high-alcohol, typically fortified wines like Port or Sherry.")

      Index  Unnamed: 0                                               Name  \
1095    575         524                   Risqué (Methode Ancestrale) N.V.
2075   1094          67                                Moscato d'Asti 2021
2192   1164         184                         Zagara Moscato d’Asti 2017
2224   1187         216                        Chianti Rùfina Riserva 2018
2329   1250         321                        Sourgal Moscato d'Asti 2021
...     ...         ...                                                ...
4308   2420         204                               Moscatel Dorado N.V.
4402   2474         298  San Emilio Pedro Ximénez Sherry (Solera Reserv...
4415   2480         311                          Don PX Pedro Ximenez 2017
4452   2500         348                 No. 2 White Sangria Frizzante N.V.
4456   2503         352                          Isabela Cream Sherry N.V.

      Rating  Number of Ratings  Price  \
1095     4.1                749  16.99
2075     4.2                429  16.99
2192     4.0                288  17.99
2224     4.0               3673  19.21
2329     3.9                 59  17.99
...      ...                ...    ...
4308     4.1                274  19.99
4402     4.1               3051  28.99
4415     4.1                314  24.99
4452     3.9               1589  14.99
4456     4.0                677  21.99

                                                 Region              Winery  \
1095                      France / Languedoc-Roussillon         Toad Hollow
2075  Italy / Northern Italy / Piemonte / Moscato d'...              Vietti
2192  Italy / Northern Italy / Piemonte / Moscato d'...  Marchesi di Barolo
2224  Italy / Central Italy / Toscana / Chianti / Ch...  Castello Nipozzano
2329  Italy / Northern Italy / Piemonte / Moscato d'...        Elio Perrone
...                                                 ...                 ...
4308             Spain / Andalucía / Jerez-Xérès-Sherry       César Florido
4402  Spain / Andalucía / Jerez-Xérès-Sherry / Pedro...              Lustau
4415               Spain / Andalucía / Montilla-Moriles         Toro Albalá
4452                                     Spain / Aragón               Lolea
4456             Spain / Andalucía / Jerez-Xérès-Sherry          Valdespino

                  Wine style  Alcohol content  \
1095          French Crémant              6.0
2075  Italian Moscato d'Asti              5.0
2192  Italian Moscato d'Asti              5.0
2224         Italian Chianti              5.0
2329  Italian Moscato d'Asti              5.0
...                      ...              ...
4308          Spanish Sherry             17.5
4402   Spanish Pedro Ximenez             17.0
4415   Spanish Pedro Ximenez             17.0
4452       Spanish Sparkling              7.0
4456          Spanish Sherry             17.5

                                          Food pairings   Bold    Tannin  \
1095  ['Shellfish', 'Poultry', 'Appetizers and snack...  53.57  46.29527
2075                    ['Fruity desserts', 'Aperitif']  30.24  46.29527
2192                    ['Fruity desserts', 'Aperitif']  28.35  46.29527
2224                        ['Beef', 'Veal', 'Poultry']  46.19  57.25000
2329                    ['Fruity desserts', 'Aperitif']  30.09  46.29527
...                                                 ...    ...       ...
4308  ['Mature and hard cheese', 'Appetizers and sna...  67.73  46.29527
4402                  ['Sweet desserts', 'Blue cheese']  85.00  46.29527
4415                  ['Sweet desserts', 'Blue cheese']  85.00  46.29527
4452  ['Shellfish', 'Appetizers and snacks', 'Lean f...  40.47  46.29527
4456  ['Mature and hard cheese', 'Appetizers and sna...  67.30  46.29527

      Sweet  Acidic Country        Country_Region
1095   9.05   53.34  France  Languedoc-Roussillon
2075   9.05   34.75   Italy        Northern Italy
2192   9.05   34.56   Italy        Northern Italy
2224   4.35   64.09   Italy         Central Italy
2329   9.05   34.72   Italy        Northern Italy
...     ...     ...     ...                   ...
4308  70.75   64.71   Spain             Andalucía
4402  85.00   43.48   Spain             Andalucía
4415  85.00   42.59   Spain             Andalucía
4452   9.05   44.70   Spain                Aragón
4456  69.93   60.76   Spain             Andalucía

[144 rows x 17 columns]
Wines below 9% alcohol are low-alcohol wines, like Moscato or low-alcohol Riesling. Wines above 16% are high-alcohol, typically fortified wines like Port or Sherry.

In [86]:
import os

# Ensure the directory exists
output_path = "data/processed/process_wine_data.csv"
output_dir = os.path.dirname(output_path)

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Save the cleaned and processed data to a new CSV file
wine_df.to_csv(output_path, index=False)