In [2]:
import pandas as pd
import os
import glob

ModuleNotFoundError: No module named 'pandas'

In [ ]:
# Load CSV files into a list
# csv_files = ["https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/Australia_Wine_Stats.csv",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/Chile_Wine_Stats.csv",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/France_Wine_Stats.csv",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/Italy_Wine_Stats.csv", 
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/New%20Zealand_Wine_Stats.csv",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/Portugal_Wine_Stats.csv",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/Spain_Wine_Stats.csv ",
#              "https://raw.githubusercontent.com/YasithaNV2001/Wine_Data_Dashbord/refs/heads/Data_Preparation/Wine_Stats/USA_Wine_Stats.csv"]  




csv_files = glob.glob("../Wine_Stats/*.csv") 
data_frames = [pd.read_csv(file) for file in csv_files]

# Concatenate into a single DataFrame
wine_df = pd.concat(data_frames, ignore_index=True)

# Display the first few rows
wine_df.head()

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic
0,0,Fields Of Joy Shiraz 2014,4.0,203,28.99,Australia / South Australia / Mount Lofty Rang...,Two Hands,Australian Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,47.13000,20.62,43.570
1,1,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.500000,"Mourvedre, Shiraz/Syrah, Grenache","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.000
2,2,Passion has Red Lips 2020,3.8,350,27.50,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.780
3,3,The Hermit Crab Viognier - Marsanne 2018,3.8,1026,16.99,Australia / South Australia / Fleurieu / McLar...,d'Arenberg,NaN,13.794543,NaN,[],61.73,46.29527,9.05,53.555
4,4,Cabernet Sauvignon (Batch No. 1 & 3) 2019,3.8,969,14.99,Australia / South Eastern Australia,Gentleman's Collection,Australian Cabernet Sauvignon,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",76.34,49.36000,16.02,47.890

In [ ]:
# Display the first few rows of the DataFrame
print(wine_df.head())

# Display the DataFrame structure (columns and data types)
print(wine_df.info())

# Summary statistics for numerical columns
print(wine_df.describe())

   Unnamed: 0                                       Name  Rating  \
0           0                  Fields Of Joy Shiraz 2014     4.0
1           1                          Shotfire GSM 2018     3.9
2           2                  Passion has Red Lips 2020     3.8
3           3   The Hermit Crab Viognier - Marsanne 2018     3.8
4           4  Cabernet Sauvignon (Batch No. 1 & 3) 2019     3.8

   Number of Ratings  Price  \
0                203  28.99
1                 36  19.49
2                350  27.50
3               1026  16.99
4                969  14.99

                                              Region                  Winery  \
0  Australia / South Australia / Mount Lofty Rang...               Two Hands
1              Australia / South Australia / Barossa            Thorn-Clarke
2  Australia / South Australia / Fleurieu / McLar...        Some Young Punks
3  Australia / South Australia / Fleurieu / McLar...              d'Arenberg
4                Australia / South Eastern Australia  Gentleman's Collection

                      Wine style  Alcohol content  \
0              Australian Shiraz        13.794543
1     Australian Rhône Blend Red        14.500000
2   Australian Cabernet - Shiraz        13.794543
3                            NaN        13.794543
4  Australian Cabernet Sauvignon        13.794543

                              Grapes  \
0                                NaN
1  Mourvedre, Shiraz/Syrah, Grenache
2                                NaN
3                                NaN
4                                NaN

                                       Food pairings   Bold    Tannin  Sweet  \
0  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  47.13000  20.62
1  ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']  85.00  50.63000   9.05
2                        ['Beef', 'Lamb', 'Poultry']  85.00  49.37000   8.19
3                                                 []  61.73  46.29527   9.05
4                        ['Beef', 'Lamb', 'Poultry']  76.34  49.36000  16.02

   Acidic
0  43.570
1  43.000
2  44.780
3  53.555
4  47.890
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5145 entries, 0 to 5144
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5145 non-null   int64
 1   Name               5145 non-null   object
 2   Rating             5145 non-null   float64
 3   Number of Ratings  5145 non-null   int64
 4   Price              5145 non-null   float64
 5   Region             5145 non-null   object
 6   Winery             5142 non-null   object
 7   Wine style         4624 non-null   object
 8   Alcohol content    5145 non-null   float64
 9   Grapes             2977 non-null   object
 10  Food pairings      5145 non-null   object
 11  Bold               5145 non-null   float64
 12  Tannin             5145 non-null   float64
 13  Sweet              5145 non-null   float64
 14  Acidic             5145 non-null   float64
dtypes: float64(7), int64(2), object(6)
memory usage: 603.1+ KB
None
        Unnamed: 0       Rating  Number of Ratings        Price  \
count  5145.000000  5145.000000        5145.000000  5145.000000
mean    503.271914     4.000292         601.032653    27.424618
std     406.492427     0.157726        2725.500208    10.645818
min       0.000000     3.700000          25.000000     6.500000
25%     164.000000     3.900000          73.000000    19.980000
50%     377.000000     4.000000         189.000000    25.990000
75%     790.000000     4.100000         483.000000    34.000000
max    1436.000000     4.600000      159937.000000   155.000000

       Alcohol content         Bold       Tannin        Sweet       Acidic
count      5145.000000  5145.000000  5145.000000  5145.000000  5145.000000
mean         13.794363    57.990384    46.293535    12.259602    54.096125
std           1.242644    19.081310    11.092394    12.306948    14.463969
min           5.000000     0.060000     1.400000     0.010000     7.230000
25%          13.500000    45.330000    46.295270     6.230000    44.700000
50%          13.794543    61.730000    46.295270     9.050000    53.555000
75%          14.000000    69.620000    48.610000    13.200000    63.550000
max          20.500000    85.000000    85.000000    85.000000    85.000000

In [ ]:
# Split the 'Region' column by '/' and create separate columns for 'Country' and 'Region Detail'
wine_df['Country'] = wine_df['Region'].str.split('/').str[0].str.strip()  # First part as 'Country'
wine_df['Country_Region'] = wine_df['Region'].str.split('/').str[1].str.strip()  # Second part as 'Country_Region'

# Display the first few rows to confirm the changes
print(wine_df[['Region', 'Country', 'Country_Region']].head())
print(wine_df)

                                              Region    Country  \
0  Australia / South Australia / Mount Lofty Rang...  Australia
1              Australia / South Australia / Barossa  Australia
2  Australia / South Australia / Fleurieu / McLar...  Australia
3  Australia / South Australia / Fleurieu / McLar...  Australia
4                Australia / South Eastern Australia  Australia

            Country_Region
0          South Australia
1          South Australia
2          South Australia
3          South Australia
4  South Eastern Australia
      Unnamed: 0                                               Name  Rating  \
0              0                          Fields Of Joy Shiraz 2014     4.0
1              1                                  Shotfire GSM 2018     3.9
2              2                          Passion has Red Lips 2020     3.8
3              3           The Hermit Crab Viognier - Marsanne 2018     3.8
4              4          Cabernet Sauvignon (Batch No. 1 & 3) 2019     3.8
...          ...                                                ...     ...
5140         667  Katherine Goldschmidt Stonemason Hill Cabernet...     4.1
5141         668                           Pessimist Red Blend 2020     4.0
5142         669                            Cabernet Sauvignon 2013     3.8
5143         670                                  Petit Verdot 2017     4.2
5144         671                          Freakshow Chardonnay 2020     3.8

      Number of Ratings  Price  \
0                   203  28.99
1                    36  19.49
2                   350  27.50
3                  1026  16.99
4                   969  14.99
...                 ...    ...
5140                 80  25.99
5141                574  17.99
5142               4612  34.99
5143                 53  34.99
5144                160  17.99

                                                 Region  \
0     Australia / South Australia / Mount Lofty Rang...
1                 Australia / South Australia / Barossa
2     Australia / South Australia / Fleurieu / McLar...
3     Australia / South Australia / Fleurieu / McLar...
4                   Australia / South Eastern Australia
...                                                 ...
5140  United States / California / North Coast / Son...
5141  United States / California / Central Coast / S...
5142  United States / California / Central Coast / S...
5143  United States / California / Central Coast / S...
5144  United States / California / Central Valley / ...

                      Winery                      Wine style  Alcohol content  \
0                  Two Hands               Australian Shiraz        13.794543
1               Thorn-Clarke      Australian Rhône Blend Red        14.500000
2           Some Young Punks    Australian Cabernet - Shiraz        13.794543
3                 d'Arenberg                             NaN        13.794543
4     Gentleman's Collection   Australian Cabernet Sauvignon        13.794543
...                      ...                             ...              ...
5140   Goldschmidt Vineyards  Californian Cabernet Sauvignon        13.794543
5141                    DAOU           Californian Red Blend        15.200000
5142          Liberty School  Californian Cabernet Sauvignon        13.500000
5143                  Opaque                             NaN        13.794543
5144    Michael David Winery          Californian Chardonnay        13.500000

                                 Grapes  \
0                                   NaN
1     Mourvedre, Shiraz/Syrah, Grenache
2                                   NaN
3                                   NaN
4                                   NaN
...                                 ...
5140                                NaN
5141                          100 Durif
5142             100 Cabernet Sauvignon
5143                                NaN
5144                     100 Chardonnay

                                          Food pairings   Bold    Tannin  \
0     ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  47.13000
1     ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']  85.00  50.63000
2                           ['Beef', 'Lamb', 'Poultry']  85.00  49.37000
3                                                    []  61.73  46.29527
4                           ['Beef', 'Lamb', 'Poultry']  76.34  49.36000
...                                                 ...    ...       ...
5140  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  82.71  48.87000
5141                ['Beef', 'Lamb', 'Veal', 'Poultry']  85.00  53.43000
5142  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  49.14000
5143                                                 []  61.73  46.29527
5144  ['Pork', 'Rich fish (salmon, tuna etc)', 'Vege...  77.65  46.29527

      Sweet  Acidic        Country           Country_Region
0     20.62  43.570      Australia          South Australia
1      9.05  43.000      Australia          South Australia
2      8.19  44.780      Australia          South Australia
3      9.05  53.555      Australia          South Australia
4     16.02  47.890      Australia  South Eastern Australia
...     ...     ...            ...                      ...
5140   7.37  43.770  United States               California
5141  15.96  61.840  United States               California
5142   9.63  42.020  United States               California
5143   9.05  53.555  United States               California
5144  33.83  47.480  United States               California

[5145 rows x 17 columns]

In [ ]:
# Remove duplicate rows from the DataFrame
# Verify by checking the shape of the DataFrame before and after
print("Before removing duplicates:", wine_df.shape)
wine_df = wine_df.drop_duplicates()
print("After removing duplicates:", wine_df.shape)
print("There are no duplicates rows")

Before removing duplicates: (5145, 17)
After removing duplicates: (5145, 17)
There are no duplicates rows

In [ ]:
#check for null values
print("\nnull records:")
print(wine_df.isnull().sum())

null records:
Unnamed: 0              0
Name                    0
Rating                  0
Number of Ratings       0
Price                   0
Region                  0
Winery                  3
Wine style            521
Alcohol content         0
Grapes               2168
Food pairings           0
Bold                    0
Tannin                  0
Sweet                   0
Acidic                  0
Country                 0
Country_Region          7
dtype: int64

In [ ]:
# Calculate and display the percentage of missing values
print("\nmissing values percentage:")
missing_percentage = (wine_df.isnull().sum() / len(wine_df)) * 100
print(missing_percentage)

missing values percentage:
Unnamed: 0            0.000000
Name                  0.000000
Rating                0.000000
Number of Ratings     0.000000
Price                 0.000000
Region                0.000000
Winery                0.058309
Wine style           10.126336
Alcohol content       0.000000
Grapes               42.137998
Food pairings         0.000000
Bold                  0.000000
Tannin                0.000000
Sweet                 0.000000
Acidic                0.000000
Country               0.000000
Country_Region        0.136054
dtype: float64

If missing values are below 10%, dropping them might be fine; above 40% may result in significant data loss,more than 40% of the 'Grapes' column is missing, it will be dropped as it's not critical for analysis.

In [ ]:
# Since more than 40% of the 'Grapes' column is missing, it will be dropped as it's not critical for analysis
wine_df = wine_df.drop(columns=['Grapes'])
print(wine_df)

      Unnamed: 0                                               Name  Rating  \
0              0                          Fields Of Joy Shiraz 2014     4.0
1              1                                  Shotfire GSM 2018     3.9
2              2                          Passion has Red Lips 2020     3.8
3              3           The Hermit Crab Viognier - Marsanne 2018     3.8
4              4          Cabernet Sauvignon (Batch No. 1 & 3) 2019     3.8
...          ...                                                ...     ...
5140         667  Katherine Goldschmidt Stonemason Hill Cabernet...     4.1
5141         668                           Pessimist Red Blend 2020     4.0
5142         669                            Cabernet Sauvignon 2013     3.8
5143         670                                  Petit Verdot 2017     4.2
5144         671                          Freakshow Chardonnay 2020     3.8

      Number of Ratings  Price  \
0                   203  28.99
1                    36  19.49
2                   350  27.50
3                  1026  16.99
4                   969  14.99
...                 ...    ...
5140                 80  25.99
5141                574  17.99
5142               4612  34.99
5143                 53  34.99
5144                160  17.99

                                                 Region  \
0     Australia / South Australia / Mount Lofty Rang...
1                 Australia / South Australia / Barossa
2     Australia / South Australia / Fleurieu / McLar...
3     Australia / South Australia / Fleurieu / McLar...
4                   Australia / South Eastern Australia
...                                                 ...
5140  United States / California / North Coast / Son...
5141  United States / California / Central Coast / S...
5142  United States / California / Central Coast / S...
5143  United States / California / Central Coast / S...
5144  United States / California / Central Valley / ...

                      Winery                      Wine style  Alcohol content  \
0                  Two Hands               Australian Shiraz        13.794543
1               Thorn-Clarke      Australian Rhône Blend Red        14.500000
2           Some Young Punks    Australian Cabernet - Shiraz        13.794543
3                 d'Arenberg                             NaN        13.794543
4     Gentleman's Collection   Australian Cabernet Sauvignon        13.794543
...                      ...                             ...              ...
5140   Goldschmidt Vineyards  Californian Cabernet Sauvignon        13.794543
5141                    DAOU           Californian Red Blend        15.200000
5142          Liberty School  Californian Cabernet Sauvignon        13.500000
5143                  Opaque                             NaN        13.794543
5144    Michael David Winery          Californian Chardonnay        13.500000

                                          Food pairings   Bold    Tannin  \
0     ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  47.13000
1     ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']  85.00  50.63000
2                           ['Beef', 'Lamb', 'Poultry']  85.00  49.37000
3                                                    []  61.73  46.29527
4                           ['Beef', 'Lamb', 'Poultry']  76.34  49.36000
...                                                 ...    ...       ...
5140  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  82.71  48.87000
5141                ['Beef', 'Lamb', 'Veal', 'Poultry']  85.00  53.43000
5142  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  49.14000
5143                                                 []  61.73  46.29527
5144  ['Pork', 'Rich fish (salmon, tuna etc)', 'Vege...  77.65  46.29527

      Sweet  Acidic        Country           Country_Region
0     20.62  43.570      Australia          South Australia
1      9.05  43.000      Australia          South Australia
2      8.19  44.780      Australia          South Australia
3      9.05  53.555      Australia          South Australia
4     16.02  47.890      Australia  South Eastern Australia
...     ...     ...            ...                      ...
5140   7.37  43.770  United States               California
5141  15.96  61.840  United States               California
5142   9.63  42.020  United States               California
5143   9.05  53.555  United States               California
5144  33.83  47.480  United States               California

[5145 rows x 16 columns]

In [ ]:
#The 'Wine style' column has about 10% missing values, so we will drop rows with missing values in this column
wine_df = wine_df.dropna(subset=['Wine style'])

In [ ]:
# Display the updated DataFrame info
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4624 entries, 0 to 5144
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4624 non-null   int64
 1   Name               4624 non-null   object
 2   Rating             4624 non-null   float64
 3   Number of Ratings  4624 non-null   int64
 4   Price              4624 non-null   float64
 5   Region             4624 non-null   object
 6   Winery             4624 non-null   object
 7   Wine style         4624 non-null   object
 8   Alcohol content    4624 non-null   float64
 9   Food pairings      4624 non-null   object
 10  Bold               4624 non-null   float64
 11  Tannin             4624 non-null   float64
 12  Sweet              4624 non-null   float64
 13  Acidic             4624 non-null   float64
 14  Country            4624 non-null   object
 15  Country_Region     4620 non-null   object
dtypes: float64(7), int64(2), object(7)
memory usage: 614.1+ KB

In [ ]:
# Create a new 'index' column starting from 1
wine_df.insert(0, "Index", range(1, len(wine_df) + 1))
wine_df.drop(columns=['Unnamed: 0'])

,Index,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Food pairings,Bold,Tannin,Sweet,Acidic,Country,Country_Region
0,1,Fields Of Joy Shiraz 2014,4.0,203,28.99,Australia / South Australia / Mount Lofty Rang...,Two Hands,Australian Shiraz,13.794543,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,47.13000,20.62,43.57,Australia,South Australia
1,2,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.500000,"['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.00,Australia,South Australia
2,3,Passion has Red Lips 2020,3.8,350,27.50,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,13.794543,"['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.78,Australia,South Australia
4,4,Cabernet Sauvignon (Batch No. 1 & 3) 2019,3.8,969,14.99,Australia / South Eastern Australia,Gentleman's Collection,Australian Cabernet Sauvignon,13.794543,"['Beef', 'Lamb', 'Poultry']",76.34,49.36000,16.02,47.89,Australia,South Eastern Australia
5,5,Passion has Red Lips 2014,3.8,648,18.49,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,14.500000,"['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.78,Australia,South Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5139,4620,Dry Riesling 2015,3.9,184,24.99,United States / California / North Coast / Nap...,Trefethen,Californian Riesling,12.500000,"['Pork', 'Shellfish', 'Spicy food', 'Poultry',...",41.61,46.29527,1.21,69.68,United States,California
5140,4621,Katherine Goldschmidt Stonemason Hill Cabernet...,4.1,80,25.99,United States / California / North Coast / Son...,Goldschmidt Vineyards,Californian Cabernet Sauvignon,13.794543,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",82.71,48.87000,7.37,43.77,United States,California
5141,4622,Pessimist Red Blend 2020,4.0,574,17.99,United States / California / Central Coast / S...,DAOU,Californian Red Blend,15.200000,"['Beef', 'Lamb', 'Veal', 'Poultry']",85.00,53.43000,15.96,61.84,United States,California
5142,4623,Cabernet Sauvignon 2013,3.8,4612,34.99,United States / California / Central Coast / S...,Liberty School,Californian Cabernet Sauvignon,13.500000,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,49.14000,9.63,42.02,United States,California
5144,4624,Freakshow Chardonnay 2020,3.8,160,17.99,United States / California / Central Valley / ...,Michael David Winery,Californian Chardonnay,13.500000,"['Pork', 'Rich fish (salmon, tuna etc)', 'Vege...",77.65,46.29527,33.83,47.48,United States,California

In [ ]:
#Display the updated Dataframe
print(wine_df)

      Index  Unnamed: 0                                               Name  \
0         1           0                          Fields Of Joy Shiraz 2014
1         2           1                                  Shotfire GSM 2018
2         3           2                          Passion has Red Lips 2020
4         4           4          Cabernet Sauvignon (Batch No. 1 & 3) 2019
5         5           5                          Passion has Red Lips 2014
...     ...         ...                                                ...
5139   4620         666                                  Dry Riesling 2015
5140   4621         667  Katherine Goldschmidt Stonemason Hill Cabernet...
5141   4622         668                           Pessimist Red Blend 2020
5142   4623         669                            Cabernet Sauvignon 2013
5144   4624         671                          Freakshow Chardonnay 2020

      Rating  Number of Ratings  Price  \
0        4.0                203  28.99
1        3.9                 36  19.49
2        3.8                350  27.50
4        3.8                969  14.99
5        3.8                648  18.49
...      ...                ...    ...
5139     3.9                184  24.99
5140     4.1                 80  25.99
5141     4.0                574  17.99
5142     3.8               4612  34.99
5144     3.8                160  17.99

                                                 Region  \
0     Australia / South Australia / Mount Lofty Rang...
1                 Australia / South Australia / Barossa
2     Australia / South Australia / Fleurieu / McLar...
4                   Australia / South Eastern Australia
5     Australia / South Australia / Fleurieu / McLar...
...                                                 ...
5139  United States / California / North Coast / Nap...
5140  United States / California / North Coast / Son...
5141  United States / California / Central Coast / S...
5142  United States / California / Central Coast / S...
5144  United States / California / Central Valley / ...

                      Winery                      Wine style  Alcohol content  \
0                  Two Hands               Australian Shiraz        13.794543
1               Thorn-Clarke      Australian Rhône Blend Red        14.500000
2           Some Young Punks    Australian Cabernet - Shiraz        13.794543
4     Gentleman's Collection   Australian Cabernet Sauvignon        13.794543
5           Some Young Punks    Australian Cabernet - Shiraz        14.500000
...                      ...                             ...              ...
5139               Trefethen            Californian Riesling        12.500000
5140   Goldschmidt Vineyards  Californian Cabernet Sauvignon        13.794543
5141                    DAOU           Californian Red Blend        15.200000
5142          Liberty School  Californian Cabernet Sauvignon        13.500000
5144    Michael David Winery          Californian Chardonnay        13.500000

                                          Food pairings   Bold    Tannin  \
0     ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  47.13000
1     ['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']  85.00  50.63000
2                           ['Beef', 'Lamb', 'Poultry']  85.00  49.37000
4                           ['Beef', 'Lamb', 'Poultry']  76.34  49.36000
5                           ['Beef', 'Lamb', 'Poultry']  85.00  49.37000
...                                                 ...    ...       ...
5139  ['Pork', 'Shellfish', 'Spicy food', 'Poultry',...  41.61  46.29527
5140  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  82.71  48.87000
5141                ['Beef', 'Lamb', 'Veal', 'Poultry']  85.00  53.43000
5142  ['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...  85.00  49.14000
5144  ['Pork', 'Rich fish (salmon, tuna etc)', 'Vege...  77.65  46.29527

      Sweet  Acidic        Country           Country_Region
0     20.62   43.57      Australia          South Australia
1      9.05   43.00      Australia          South Australia
2      8.19   44.78      Australia          South Australia
4     16.02   47.89      Australia  South Eastern Australia
5      8.19   44.78      Australia          South Australia
...     ...     ...            ...                      ...
5139   1.21   69.68  United States               California
5140   7.37   43.77  United States               California
5141  15.96   61.84  United States               California
5142   9.63   42.02  United States               California
5144  33.83   47.48  United States               California

[4624 rows x 17 columns]

In [ ]:
# Function to identify outliers based on the 1st and 99th percentiles
def find_percentile_outliers(df, columns, lower_percentile=1, upper_percentile=99):
    outlier_rows = {}

    for column in columns:
        # Calculate the lower and upper bounds based on percentiles
        lower_bound = df[column].quantile(lower_percentile / 100)
        upper_bound = df[column].quantile(upper_percentile / 100)
        
        # Find rows where values are outside the bounds
        outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)].index
        
        # Get the corresponding row numbers for these outliers
        outlier_row_numbers = df.loc[outliers, 'Index'].tolist()
        
        # Store the row numbers of outliers for each column
        outlier_rows[column] = outlier_row_numbers
    
    return outlier_rows

In [ ]:
#Columns to check for outliers
columns_to_check = ['Rating', 'Price', 'Bold', 'Tannin', 'Sweet', 'Acidic']

In [ ]:
# Find the rows with outliers in the specified columns
outlier_rows = find_percentile_outliers(wine_df, columns_to_check, lower_percentile=1, upper_percentile=99)

In [ ]:
# Print the outlier row numbers for each column
for column, rows in outlier_rows.items():
    print(f"Outliers for column '{column}':")
    print(rows)
    print("\n")

Outliers for column 'Rating':
[101, 307, 746, 1403, 1521, 1656, 2113, 2227, 2662, 2913, 3418, 3537, 3870, 4279]


Outliers for column 'Price':
[90, 130, 148, 190, 196, 210, 217, 218, 341, 378, 393, 396, 457, 461, 509, 512, 588, 718, 774, 779, 915, 922, 951, 999, 1005, 1020, 1171, 1225, 1277, 1289, 1313, 1360, 1429, 1451, 1480, 1484, 1529, 1552, 1593, 1595, 1626, 1635, 1642, 1689, 1716, 1802, 2122, 2132, 2153, 2274, 2428, 2674, 2769, 2867, 2994, 3132, 3140, 3167, 3168, 3182, 3229, 3250, 3254, 3266, 3291, 3360, 3364, 3376, 3467, 3491, 3532, 3578, 3597, 3600, 3628, 3680, 3744, 3748, 3768, 3798, 3821, 3823, 3862, 3933, 3989, 4104, 4240, 4283, 4602]


Outliers for column 'Bold':
[564, 584, 677, 694, 726, 727, 734, 857, 905, 989, 1051, 1058, 1077, 1109, 1133, 1183, 1197, 1238, 1247, 1304, 1376, 1383, 1388, 1409, 1420, 1421, 1445, 1487, 1523, 1533, 1558, 1590, 1620, 1622, 1627, 1629, 1638, 1674, 1694, 3206, 3323, 3532, 3701, 3728, 3781, 3833, 3944]


Outliers for column 'Tannin':
[201, 351, 352, 354, 368, 384, 385, 410, 417, 447, 459, 497, 499, 560, 584, 639, 646, 647, 677, 711, 727, 734, 791, 805, 823, 843, 875, 912, 959, 989, 992, 1051, 1058, 1109, 1133, 1183, 1229, 1238, 1341, 1383, 1388, 1409, 1464, 1487, 1523, 1558, 1572, 1590, 1627, 1629, 1674, 1694, 1717, 1719, 1720, 1776, 1848, 1872, 1885, 1903, 1934, 1940, 1949, 1985, 2048, 2051, 2061, 2085, 2139, 2171, 2199, 2205, 2213, 2236, 2239, 2243, 2286, 2368, 2391, 2398, 2431, 2450, 2541, 2615, 2636, 2675, 2699, 2730, 2782, 2807, 2958, 2973, 3004, 4082]


Outliers for column 'Sweet':
[511, 525, 542, 554, 602, 712, 740, 899, 984, 1048, 1187, 1203, 1259, 1263, 1294, 1320, 1324, 1372, 1452, 1460, 1495, 1497, 1534, 1588, 1591, 1637, 1674, 1680, 1827, 1916, 1935, 2266, 2368, 2510, 2709, 2753, 2770, 2885, 3102, 3103, 3165, 3200, 3443, 3836, 4025, 4281, 4470]


Outliers for column 'Acidic':
[28, 62, 83, 140, 225, 247, 277, 351, 352, 399, 1828, 1942, 2068, 2150, 2258, 2312, 2329, 2760, 2773, 2877, 2887, 2902, 4028, 4090, 4103, 4106, 4132, 4139, 4146, 4175, 4226, 4291, 4304, 4318, 4337, 4344, 4346, 4372, 4418, 4446, 4469, 4534, 4550, 4560, 4564, 4565, 4574]

In [ ]:
# Interpretation of the outliers
print("Interpretation:")
print("Outliers in the 'Rating,' 'Price,' 'Tannin,' 'Sweet,' 'Acidic,' and 'Bold' columns in wines are considered valid and should not be" 
      "removed due to domain-specific reasons. These outliers may represent rare but legitimate cases, such as premium products or exceptional"
      " ratings, which are important for accurately capturing the full range of wine characteristics.")

Interpretation:
Outliers in the 'Rating,' 'Price,' 'Tannin,' 'Sweet,' 'Acidic,' and 'Bold' columns in wines are considered valid and should not beremoved due to domain-specific reasons. These outliers may represent rare but legitimate cases, such as premium products or exceptional ratings, which are important for accurately capturing the full range of wine characteristics.

In [ ]:
#Check for wines with alcohol content above 16% or below 9%
non_regular_wines = wine_df[(wine_df['Alcohol content'] > 16) | (wine_df['Alcohol content'] < 9)]
print(non_regular_wines)
print("Wines below 9% alcohol are low-alcohol wines, like Moscato or low-alcohol Riesling. Wines above 16% are high-alcohol, typically fortified wines like Port or Sherry.")

      Index  Unnamed: 0                                               Name  \
1095    914         524                   Risqué (Methode Ancestrale) N.V.
2075   1781          67                                Moscato d'Asti 2021
2192   1892         184                         Zagara Moscato d’Asti 2017
2224   1924         216                        Chianti Rùfina Riserva 2018
2329   2020         321                        Sourgal Moscato d'Asti 2021
...     ...         ...                                                ...
4308   3847         204                               Moscatel Dorado N.V.
4402   3927         298  San Emilio Pedro Ximénez Sherry (Solera Reserv...
4415   3938         311                          Don PX Pedro Ximenez 2017
4452   3970         348                 No. 2 White Sangria Frizzante N.V.
4456   3974         352                          Isabela Cream Sherry N.V.

      Rating  Number of Ratings  Price  \
1095     4.1                749  16.99
2075     4.2                429  16.99
2192     4.0                288  17.99
2224     4.0               3673  19.21
2329     3.9                 59  17.99
...      ...                ...    ...
4308     4.1                274  19.99
4402     4.1               3051  28.99
4415     4.1                314  24.99
4452     3.9               1589  14.99
4456     4.0                677  21.99

                                                 Region              Winery  \
1095                      France / Languedoc-Roussillon         Toad Hollow
2075  Italy / Northern Italy / Piemonte / Moscato d'...              Vietti
2192  Italy / Northern Italy / Piemonte / Moscato d'...  Marchesi di Barolo
2224  Italy / Central Italy / Toscana / Chianti / Ch...  Castello Nipozzano
2329  Italy / Northern Italy / Piemonte / Moscato d'...        Elio Perrone
...                                                 ...                 ...
4308             Spain / Andalucía / Jerez-Xérès-Sherry       César Florido
4402  Spain / Andalucía / Jerez-Xérès-Sherry / Pedro...              Lustau
4415               Spain / Andalucía / Montilla-Moriles         Toro Albalá
4452                                     Spain / Aragón               Lolea
4456             Spain / Andalucía / Jerez-Xérès-Sherry          Valdespino

                  Wine style  Alcohol content  \
1095          French Crémant              6.0
2075  Italian Moscato d'Asti              5.0
2192  Italian Moscato d'Asti              5.0
2224         Italian Chianti              5.0
2329  Italian Moscato d'Asti              5.0
...                      ...              ...
4308          Spanish Sherry             17.5
4402   Spanish Pedro Ximenez             17.0
4415   Spanish Pedro Ximenez             17.0
4452       Spanish Sparkling              7.0
4456          Spanish Sherry             17.5

                                          Food pairings   Bold    Tannin  \
1095  ['Shellfish', 'Poultry', 'Appetizers and snack...  53.57  46.29527
2075                    ['Fruity desserts', 'Aperitif']  30.24  46.29527
2192                    ['Fruity desserts', 'Aperitif']  28.35  46.29527
2224                        ['Beef', 'Veal', 'Poultry']  46.19  57.25000
2329                    ['Fruity desserts', 'Aperitif']  30.09  46.29527
...                                                 ...    ...       ...
4308  ['Mature and hard cheese', 'Appetizers and sna...  67.73  46.29527
4402                  ['Sweet desserts', 'Blue cheese']  85.00  46.29527
4415                  ['Sweet desserts', 'Blue cheese']  85.00  46.29527
4452  ['Shellfish', 'Appetizers and snacks', 'Lean f...  40.47  46.29527
4456  ['Mature and hard cheese', 'Appetizers and sna...  67.30  46.29527

      Sweet  Acidic Country        Country_Region
1095   9.05   53.34  France  Languedoc-Roussillon
2075   9.05   34.75   Italy        Northern Italy
2192   9.05   34.56   Italy        Northern Italy
2224   4.35   64.09   Italy         Central Italy
2329   9.05   34.72   Italy        Northern Italy
...     ...     ...     ...                   ...
4308  70.75   64.71   Spain             Andalucía
4402  85.00   43.48   Spain             Andalucía
4415  85.00   42.59   Spain             Andalucía
4452   9.05   44.70   Spain                Aragón
4456  69.93   60.76   Spain             Andalucía

[145 rows x 17 columns]
Wines below 9% alcohol are low-alcohol wines, like Moscato or low-alcohol Riesling. Wines above 16% are high-alcohol, typically fortified wines like Port or Sherry.

In [ ]:
import os

# Ensure the directory exists
output_path = "data/processed/process_wine_data.csv"
output_dir = os.path.dirname(output_path)

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Save the cleaned and processed data to a new CSV file
wine_df.to_csv(output_path, index=False)

In [ ]:

# Create new columns for each food pairing
# Explode the list values in the 'Food pairings' column
from sklearn.preprocessing import MultiLabelBinarizer

# Clean up the 'Food pairings' column if it's in string format
wine_df['Food pairings'] = wine_df['Food pairings'].apply(lambda x: eval(x) if isinstance(x, str) else x)

# Use MultiLabelBinarizer to create binary columns for each food
mlb = MultiLabelBinarizer()
food_pairing_encoded = mlb.fit_transform(wine_df['Food pairings'].dropna())

# Get the new columns and merge them into the dataframe
food_pairing_columns = pd.DataFrame(food_pairing_encoded, columns=mlb.classes_, index=wine_df['Food pairings'].dropna().index)
wine_df = pd.concat([wine_df, food_pairing_columns], axis=1)

# Fill missing values for the new columns with False (unpaired foods)
for column in mlb.classes_:
    wine_df[column] = wine_df[column].fillna(False).astype(bool)

# Display the updated DataFrame
print(wine_df.head())

# Save the updated DataFrame to a CSV file
output_path = "data/processed/process_wine_data_with_food_pairings.csv"
wine_df.to_csv(output_path, index=False)

ModuleNotFoundError: No module named 'sklearn'